### ISSUE TITLE
Docker Image Conversion

### ISSUE THREAD

**Issue by gatesry** [erikespinoza/v4raider#1]
Hello! I'm pretty new to Docker/Github/Coding, but I'm trying to get this build automated on Docker Hub. My goal is to run it in Unraid (Hypervisor), within a container. It doesn't appear that I can run the steps in the README at the console of my Unraid HV. 

I tried forking it, and then setting up a build to DockerHub, but it fails because it's looking for Dockerfile @ ./Dockerfile.

Any advice?

**Comment by erikespinoza** [comment]
This repo doesn't build any containers. It uses pre-built ones.

You can always explore their repos.
https://github.com/linuxserver/docker-wireguard
https://github.com/traefik/traefik

But I suspect DockerHub builds won't help you here, as I don't think I fully understand your issue.
