### ISSUE TITLE
Best approach for egress or outbound traffic

### ISSUE THREAD

**Issue by engineeringsys** [erikespinoza/v4raider#4]
Thanks for creating this project, very simple and works well for a single docker host setup.

Ingress traffic works flawlessly.  But what about egress traffic?  Given how the container is setup if one wanted all of their docker containers connected to the dmz network to default egress via the wireguard container, what is a good way to set that up?

I believe you would have to set some sort of route within the container to say only route egress traffic via wg0 inside of container(wireguard).  Any thoughts on how to best implement this?

**Comment by erikespinoza** [comment]
Sorry, but egress is out of scope for this project.
