### ISSUE TITLE
Export Port for Traefik to access it from local Network

### ISSUE THREAD

**Issue by PersistentCloud** [erikespinoza/v4raider#5]
Hello,
your Tutorial works like a charm after I found out to open the Wireguard UDP Port within my VPS Firewall. I just wanted to ask how I can access the Traefik UI without exposing it to the net. Can I somehow expose the 8080 port to access it only within my local network?

**Comment by geekscrapy** [comment]
+1

**Comment by erikespinoza** [comment]
You'll need to forward the port, say 8080. You'll also need to add a route for your local network inside the container. More info here. https://github.com/erikespinoza/v4raider/issues/3#issuecomment-813753562
